# config.yml

# Set the theme for your GitHub Pages site
theme: jekyll-theme-minimal

# Enable GitHub Pages
# If your repository is private, you might need to change this to "true"
# to enable GitHub Pages for the private repository.
remote_theme: jekyll/minimal

# Site settings
title: Aneena V G
description: Computer Science & Engineering Undergraduate

# GitHub repository settings
repository: AneenaVG/AneenaVG.github.io
